baseURL = "https://fionntan.github.io/"
languageCode = "en-uk"
title = "Ah, Grand So"
theme = "charaka-hugo-theme"
posts = "/:year/:month/:title/"
# copyright = "&copy; <a href=\"https://github.com/natarajmb\">Nataraj Basappa</a> 2018"
# copyright = "&copy; Fionntán O'Donnell"
disqusShortname = ""
googleAnalytics = ""

[params]

[params.highlight]
  style = "zenburn"

# [[params.social]]
#   url = "about.html"
#   fa_icon = "fas fa-info" 

# [[params.social]]
#   url = "https://github.com/natarajmb"
#   fa_icon = "fab fa-github"

# [[params.social]]
#   url = "https://www.linkedin.com/in/natarajmb/"
#   fa_icon = "fab fa-linkedin-in"

[[params.social]]
  url = "https://twitter.com/fionntan"
  fa_icon = "fab fa-twitter"